### ISSUE TITLE
Diseño Entrega 1.0

### ISSUE THREAD

**Issue by basth5** [IIC2513-2021-1/projects#1]
Una consulta, para el desarrollo de esta primera parte del proyecto, debemos hacer un diseño de la red social en modo app de escritorio o en modo de app movil? o debe ser responsive enseguida?

**Comment by Deleon20** [comment]
Hola! Aún no se ha visto en clases el uso de estilos responsive y por esto no es necesario que lo tengan en consideración para esta entrega!
