### ISSUE TITLE
[E2.1] Problemas al correr yarn dev

### ISSUE THREAD

**Issue by svaldes99** [IIC2513-2021-1/projects#102]
Hola, cuando corro yarn dev, me sale esto
![image](https://user-images.githubusercontent.com/62103274/121794384-a0bac780-cbd5-11eb-8f43-50338408a199.png)

Llevo harto rato tratando de arreglarlo, y no lo he logrado. ¿Qué puedo hacer?

**Comment by meretamal** [comment]
Puedes intentar correr `yarn install` y luego `yarn dev`?

**Comment by svaldes99** [comment]
Hice npm install y me funcionó, pero ahora me sale esto
![image](https://user-images.githubusercontent.com/62103274/121794525-dd3af300-cbd6-11eb-8af1-92f8c59a5344.png)

**Comment by humbertoortuzar** [comment]
Hola!
Quizás pueda ayudar fijarse si el las variables del `.env` con los datos de usuario y base de datos se están incorporando bien. Esto podría ser ya sea porque el paquete que usas no está bien instalado al hacer `yarn install` o porque pueden estar mal escritas en el archivo u otras cosas.
Saludos y suerte revisando!

**Comment by svaldes99** [comment]
Efectivamente era eso, pero ahora me aparece esto:

![image](https://user-images.githubusercontent.com/62103274/121817268-47db4580-cc4e-11eb-92cf-69f7430d24b6.png)

**Comment by svaldes99** [comment]
Al final era por el port, en  node_modules/sequelize/lib/dialects/postgres/connection-manager.js tuve que cambiarlo de 5432 a 5433
