### ISSUE TITLE
Instalar todo en disco duro D: | Windows

### ISSUE THREAD

**Issue by fivaldivia** [IIC2513-2021-1/projects#11]
Hola, estoy teniendo problemas para instalar las cosas ya que mi disco C está con memoria casi completa. Lo que estoy tratando es instalar todo desde `bash` ubicándome en la carpeta D pero parece no funcionar ya que me tira error de falta de memoria. Uso Windows con Ubuntu 18.04, quería saber si alguno me puede ayudar como puedo hacerlo, ya que son muchas cosas que instalar. Dejo referencia de lo que me sale al correr el comando `curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash`:
![image](https://user-images.githubusercontent.com/42453679/116116421-249e0c00-a689-11eb-8423-ab072e2355f5.png)
Y mi memoria esta así:
![image](https://user-images.githubusercontent.com/42453679/116116517-3c759000-a689-11eb-85ca-0ec949cb04f9.png)

PD: ya realizé  ` sudo apt-get clean` y  `sudo apt-get autoclean`.

**Comment by dhvasquez** [comment]
Hola, nose muy biencomo tienes montada las particiones de los discos en WSL (por lo general estan en ```/mnt/<disco>```, pero por lo que dice el comando, esta bien montado. Independiente de eso, cuando instalas ```nvm```, este no se instala en una carpeta que tu eligas, sino que se instala en el sistema, es decir sigue en ```C:``` (y en una carpeta de WSL por defecto), asique al parecer vas a tener que hacer espacio en tu disco principal.  

Y un par de cosas antes de que sigas:
- El proyecto no es recomendable correrlo en un una carpeta montada (como tus tipicos directorios de Windows), porque lo mas probable es que corran mal, esto debido a que WSL usa un sistema de archivos distinto a windows, y si bien puede montar un disco de windows y leerlo, no lo maneja bien. Lo mejor es que hagas espacio y lo manejes en carpetas nativas de wsl (```/home/florencia``` es un directorio recomendable). En caso de que quieras abrir el directorio nativo desde el explorador de Windows, puedes usar el comando ```explorer.exe .```, para indicar que quieres abrir el programa explorer.exe en el directorio que estas apuntando.
- Tanto el proyecto como ```nvm``` no usan tanto espacio, asi que es mejor que que liberes un par de GB para correr el proyecto en directorios nativos.

Saludos!
