### ISSUE TITLE
[E2.2] Error en DELETE

### ISSUE THREAD

**Issue by veneguitas** [IIC2513-2021-1/projects#118]
Hola! Estoy haciendo endpoints de DELETE, pero ocurre algo extraño, al probar el endpoint en Postman me tira el mensaje de "An error has occurred", al revisar la consola dice que si se eliminó ya sea la propiedad o el usuario. Además, la consola tira esto:

http-errors deprecated non-error status code; use only 4xx or 5xx status codes node_modules/koa/lib/context.js:97:11

Busqué qué podría ser, pero no entendí mucho el problema. Hasta revisé la base de datos y si se eliminan los datos.

Saludos!

**Comment by sivicencio** [comment]
Hola. ¿Podrías por favor adjuntar los resultados de tu búsqueda? A priori sin ver nada de tu código es difícil saber por qué un error tan genérico como "An error has occurred" te aparece.
