### ISSUE TITLE
Problema en Pull Request del Fronted

### ISSUE THREAD

**Issue by Benjale** [IIC2513-2021-1/projects#119]
Hola! quiero realizar un pull request al main con el esqueleto del fronted de mi proyecto (creación del react), pero cada vez que lo intento me tira el siguiente error en Test and linters
![image](https://user-images.githubusercontent.com/62115136/123889034-ada02080-d922-11eb-90ff-704ae943d7c6.png)
Con este error no puedo realizar el pull request y, por lo tanto, no puedo actualizar el main de mi repositorio. 
He intentado distintas cosas como instalar sequelize con yarn o agregar la file de sequelizerc, pero nada me ha funcionado

**Comment by meretamal** [comment]
Hola 😁, parece que configuraron mal tu repositorio y pusieron la action del backend. Voy a hablar para que lo arreglen

**Comment by Benjale** [comment]
> Hola 😁, parece que configuraron mal tu repositorio y pusieron la action del backend. Voy a hablar para que lo arreglen

Quedo atento

**Comment by B-Dominguez** [comment]
Hola @Benjale, su ayudante de seguimiento no está disponible pero me metí yo a arreglar el problema. Ya está actualizada su action, así que si actualizan su PR con algún commit se debería correrer la nueva y deberían poder mergear (siempre y cuando pasen el `yarn lint`)
