### ISSUE TITLE
Fecha de entrega  1.1

### ISSUE THREAD

**Issue by perezpefaur** [IIC2513-2021-1/projects#13]
Hola! Según el calendario académico, el viernes 30 de abril hay suspensión de actividades académicas y administrativas, por lo que tengo entendido que no puede haber una entrega en este día. Queria saber si se va a mover o se mantiene? Nos juntaron muchas cosas antes de la semana de receso :(

**Comment by sivicencio** [comment]
La entrega fue aplazada para el **lunes 03 de mayo a las 23:59 hrs**. El anuncio fue hecho hace pocos minutos, al menos en la sección 1. Sin embargo, corre para **ambas secciones**.
