### ISSUE TITLE
../sequelize-cli/lib/sequelize: not found

### ISSUE THREAD

**Issue by jerrazuriz99** [IIC2513-2021-1/projects#14]
Cuando trato de correr "yarn sequelize db:migrate" me tira este erro;
![error](https://user-images.githubusercontent.com/53884268/116326330-315a5700-a792-11eb-9a13-271c6e00b2cc.PNG)

**Comment by Deleon20** [comment]
Hola!

Intenta correr  "yarn install" para instalar las dependencias del template, como sequelize :smiley:
