### ISSUE TITLE
Tiempo de compilación

### ISSUE THREAD

**Issue by Pablok98** [IIC2513-2021-1/projects#15]
¡Hola! Escribo con la esperanza de que a alguien más le haya pasado y sepa como solucionarlo. Me pasa que la aplicación se demora mucho en compilar, en comparación a lo que se veía en las capsulas al menos. El template recién generado se me compila en un minuto, pero en el video se veía casi instantáneo. 

También se demora mucho en partir aceptando requests por alguna razón :(

**Comment by dhvasquez** [comment]
Hola, asumo que estas usando WSL, y eso esta explicado en la wiki! Para que compile rapido (y ```nodemon``` derechamente funcione) debes usar las rutas nativas de WSL, un buen lugar es ```$HOME``` (```/home/<tu_usuario>``` para ser exactos).

### Razón
Cuando corres tu proyecto en el disco ```C:```, vale decir ```/mnt/c``` en WSL, estas utilizando el sistema de archivos ```NTFS``` de NT File System, que es de Windows, y si bien WSL puede leerlo, no lo maneja del todo bien. WSL en cambio, usa un sistema de archivos ```ext4```, que es de Linux, y si usas los directorios nativos, usas ese sistema de archivos el cual se comunica bien con los binarios de Linux (node, python, etc).

### Recomendaciones
- Usar un directorio nativo, debería compilar rápido y sin problemas.
- Si deseas poder visualizar los archivos de manera más interactiva, estos directorios nativos los puedes abrir desde el explorador de archivos. En la terminal, ubícate en el directorio de tu proyecto y lanza el comando ```explorer.exe .``` (con punto incluido) para inidicar que quieres abrir el directorio actual con explorer.
- Desde los directorios nativos puedes también abrir VSCode desde la carpeta, el comando es ```code .``` (con punto incluido, de hecho puedes notar el patrón "<programa> <directorio>" donde el punto indica el directorio actual.

#### Extras
* directorio = carpeta  
* En linux (y Unix en general), no existen "nombres" de discos, solo existe el directorio raíz "```/```", y todo lo demás es tratado como archivo (un disco es un archivo).
