### ISSUE TITLE
Error al correr yarn install

### ISSUE THREAD

**Issue by fivaldivia** [IIC2513-2021-1/projects#16]
Hola, pude correr el template que clone del repo de mi grupo, pero luego sin querer hice yarn add dotenv, pensando que se hacia para que funcionara el .env. Después de eso no me funciona yarn install. Dejo mi error por si alguien me puede ayudar ya que no se que puede ser, busque en internet pero no me ha funcionado nada, traté borrando caché, borrando el yarn.lock y tambien clonando nuevamente el repositorio y corriendo npm run dev. Ninguna opción me ha servido.
![image](https://user-images.githubusercontent.com/42453679/116328028-08d45c00-a796-11eb-8e16-d6f72a32fb4b.png)
Gracias!

**Comment by sivicencio** [comment]
No veo cómo ejecutar `yarn add dotenv` podría hacer que `yarn` deje de funcionar. ¿Revisaste que hayas seleccionado la versión de node correcta?

```
node -v
```

Puedes seleccionar la versión con nvm, ejecutando lo siguiente en la raíz del proyecto:
```
nvm use
```

El output debiese ser algo similar a `Now using node v12.18.3 (npm v6.14.6)` (dependiendo de la versión 12 que instalaste de Node).

**Comment by fivaldivia** [comment]
@sivicencio Hola! Si todas mis versiones están correctas, las dejo por aqui:
![image](https://user-images.githubusercontent.com/42453679/116338537-df253000-a7a9-11eb-841a-49869f0356f0.png)
Probé desinstalando e instalando nuevamente yarn, pero me salió nuevamente el mismo error...

**Comment by fivaldivia** [comment]
Hola, finalmente lo pude solucionar! Traté reiteradas veces borrando node_modules (`rm -rf node_modules`) y eliminando el yarn caché  (`yarn cache clean`). Tambien desinstalé y reinstale yarn.

**Comment by jerrazuriz99** [comment]
Hola, que hiciste para arreglar ese error?

**Comment by fivaldivia** [comment]
@jerrazuriz99 Hola! hice lo que dije antes, pero borré todos los node_modules (se me había creado uno en la consola en mi home y no me había dado cuenta, asique te recomiendo revisar bien), borre el cache de yarn, y desinstalé e instalé denuevo yarn, y si no te funciona talvez trata de clonar denuevo tu repo!

**Comment by pedroherreraj** [comment]
Creo que esto pasa porque uno de tu grupo sube la carpeta node_modules al repositorio. Es clave tener esta carpeta en el gitignore
