### ISSUE TITLE
Error con ruta servidor

### ISSUE THREAD

**Issue by Pablok98** [IIC2513-2021-1/projects#17]
¡Hola!
Por alguna razon, la dirección localhot:3000 no me está sirviendo, a pesar de que cuando hice las cápsulas originalmente me funcionó todo bien. Ahora, ni mi trabajo ni un template nuevo me logro conectar. Supuestamente se compila bien, pero no logro hacer un GET al servidor. Probé cambiando el puerto, pero no tuve suerte.

Si sirve de algo, hice un netstat y por alguna razon la dirección del socket me sale como "[::]:3000". También, si corro el programa, cambio el puerto y luego intento con el puerto anterior (cerrando el servidor obviamente), me tira un error que el puerto ya está en uso. Ayuda, algo raro pasa :(

![image](https://user-images.githubusercontent.com/53904957/116330496-aed69500-a79b-11eb-9faa-6c508ad3b9e5.png)

**Comment by sivicencio** [comment]
Por favor, avisa si lo solucionaste para poder dejar la issue como resuelta. [En esta issue](https://github.com/IIC2513-2021-1/projects/issues/20) mencionas que llevan harto trabajo, por lo que es probable que hayas solucionado el problema planteado acá.

**Comment by Pablok98** [comment]
Hola! Tuve que reiniciar varias veces el computador y luego de un tiempo funcionó😅 Asique por ahora está resuelto!
