### ISSUE TITLE
Configurara base de datos

### ISSUE THREAD

**Issue by fjcroquevielle** [IIC2513-2021-1/projects#2]
En la wiki aparecen una serie de instrucciones para comenzar con el proyecto. Bajé los programas necesarios, el template y descarge psql, sin embargo, después se me dice: 'crear la base de datos que usarás para tu aplicación (createdb ) y configurarla en src/config/database.js'. Cree la base de datos, sin embargo no se a que se refiere con configurarla. Podrían ayudarme con esto? Gracias!

**Comment by Deleon20** [comment]
Hola! Cuando se habla de configurar la base de datos se refiere a decirle a su proyecto que base de datos van a utilizar, como veran en el archivo hay algunas variables de ambiente que el template usa para la configuración de la base de datos! Como recomendacion investiga sobre las variables de ambiente y para que se usan! Más adelante haremos capsulas para este tema en particular. Ahora para la entrega 1.0 no es necesario que trabajen en el template ya que solo es necesario sitios estaticos con HTML+CSS
