### ISSUE TITLE
Caracteres utf-8 

### ISSUE THREAD

**Issue by Pablok98** [IIC2513-2021-1/projects#20]
¡Hola! Quería saber como podemos hacer para que sequelize defina la base de datos usando utf-8. Llevamos harto del trabajo y nos dimos cuenta que cuando un create tiene palabras con tilde, el modelo se crea bien (verificado con console.log) pero al momento de hacer save con sequelize, la query no es válida :( 

Existe alguna migración que podamos agregar para transformar la base de datos de alguna manera? Gracias!

**Comment by meretamal** [comment]
Hola 😁, una pregunta, qué versión de Ubuntu y Postgres tienen?

**Comment by meretamal** [comment]
Hola, si corren en postgres `\dt`, qué _encoding_ sale que usan?

**Comment by Pablok98** [comment]
Que raro, utilizando `\l` me dice que la base usa UTF8, se te ocurre porque entonces las query podrían no funcionar? A pesar de que salen en consola del servidor bien.

**Comment by Pablok98** [comment]
¡Hola! Gracias por ayudarme a darme cuenta que la base si estaba en UTF8. Hicimos algunas pruebas más específicas y al parecer es cuando un string es muy largo.
