### ISSUE TITLE
[Sequelize] [Entrega1.1] Utilizar methodo PATCH en html

### ISSUE THREAD

**Issue by Zetaku1** [IIC2513-2021-1/projects#21]
Hola!

Al intentar utilizar el metodo html patch, al correr la ruta con koa-router, este ejecuta el metodo GET.  Esto sucede aunque llame a metodos como router.patch().

Tambien al intentar utilizar el metodo html post, koa simplemente hace insert into users con un nuevo ID :
![image](https://user-images.githubusercontent.com/25071035/116485932-777aed80-a85a-11eb-9887-37f4c8a8393b.png)

No se me ocurre como actualizar la base de datos, sin crear un nuevo usuario, debido a que el metodo patch no esta siendo detectado y post crea un nuevo usuario, aunque intentemos utilizar un ID ya existente.

Hay alguna manera de obligar al router utilizar el metodo patch?

Muchas gracias de antemano.

**Comment by B-Dominguez** [comment]
Hola @Zetaku1, como se menciona en la cápsula respectiva (la de creación de autores en Gud Reads), el formulario de html solo soporta los métodos POST y GET directamente, y para realizar una request de tipo Patch, se debe hacer con un _hidden input_. 

El motivo por el que no se muestra específicamente cómo implementarlo (ni en la cápsula ni en esta respuesta), es porque en el desarrollo de aplicaciones web, fuera del ámbito de la docencia, parte muy importante del trabajo y de las habilidades requeridas son la investigación y resolución de problemas desconocidos. Por lo mismo, en este curso se intenta inculcar en general que los alumnos busquen por su cuenta información complementaria a la base aprendida en clases o material oficial, para resolver problemas. 

En general en este balance se tiende a asegurar el darles una buena base, cargando hacia el lado de dar más de lo necesario (y no menos), pero para el caso particular que planteas (formulario _patch_), se ha conversado con el cuerpo docente que no deberías tener muchos problemas encontrando la solución genérica en internet con la pista dada. De todas formas, si encuentras algún problema particular al implementarlo que te esté costando más de lo esperable, no dudes en seguir pidiendo ayuda por este medio.

PD: Ojo que el problema no es con el router, si no con el formulario html que no soporta directamente el método _Patch_, para que busques por ese lado

**Comment by sivicencio** [comment]
Complementando la respuesta de @B-Dominguez, aquí algunos recursos interesantes que te pueden dar pistas de que HTML no soporta más que `GET` y `POST`:
- [Documentación etiqueta `<form>` en MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attributes_for_form_submission), con los valores que acepta el atributo `method`
- La [discusión de la W3C](https://www.w3.org/Bugs/Public/show_bug.cgi?id=10671) sobre la posibilidad de extender los métodos HTTP que acepta un formulario (y que terminó cerrándose sin acuerdo de implementarlo)

Lo anterior no es una respuesta al problema, sino que sólo documentación que evidencia que no es posible utilizar esos métodos HTTP con un formulario HTML.
