### ISSUE TITLE
yarn error code 126

### ISSUE THREAD

**Issue by F-arellano** [IIC2513-2021-1/projects#27]
Estoy tratando de crear un nuevo modelo pero al tratar de ejecutar yarn o node me da el aviso "Command failed with exit code 126". Esto también me pasa al tratar de correr yarn dev, pero no me presenta ningún problema al ejecutar yarn start. ¿A que se podría deber?

**Comment by dhvasquez** [comment]
No es un código específico para un problema, y para resolverlo vamos a necesitar más detalles del error que lanza. Pero rescatando un poco lo que dices, lo que se me ocurre que puede estar ocurriendo es que no tengas instalados los paquetes, ya que ```yarn start``` == ```node index.js```, y node esta instalado, mientras que ```yarn dev``` = ```nodemon index.js```, y si no te corre *nodemon* o *sequelize*, es porque probablemente no los este tomando como instalados en el ambiente, para instalarlos corre ```yarn install```.

Saludos!
