### ISSUE TITLE
[entrega1.1] Publicaciones con imagenes

### ISSUE THREAD

**Issue by Zetaku1** [IIC2513-2021-1/projects#28]
Hola!

En nuestra aplicacion web, buscamos tener publicaciones con imagenes, para esto en html simplemente utilizamos imagenes estaticas guardadas en los archivos.

Ahora como nos piden CRUD de publicaciones, tenemos la duda si es necesario el guardado de imagenes subidas con middleware como [multer](https://github.com/expressjs/multer) o si se espera que utilicemos simplemente imagenes estaticas "default". 

Otra duda que tengo es si realmente se necesita middleware extra para guardar imagenes en el servidor, o si podemos con lo que ya viene instalado en el template.

Muchas gracias de antemano!

**Comment by dhvasquez** [comment]
Se espera que usen imagenes estáticas, o que guarden el link directo de una imágen sacada de google por ejemplo, y la pongan en su vista (por lo menos por ahora). Sin embargo, a futuro se les pedira que si manejan imágenes las guarden, pero para eso podrán utilizar servicios externos que guarden la imagen y les entregue el link de previsualización de vuelta (ya que es como se suele hacer en la web).

En cuanto a lo segundo, depende como deseen finalmente manejar imágenes, si quieren guardarlas directamente, deberan probablemente usar middlewares o guardarlo en la ruta, pero si usan servicios externos deberan usar las respectivas librerias del servicio, y si esta incluye middlewares, entonces usarlos.

**Comment by Zetaku1** [comment]
Muchas gracias!
