### ISSUE TITLE
Módulos no instalados E1

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2513-2021-1/projects#3]
Hola, estaba siguiendo los pasos de "comenzando el desarrollo" y me encontré con el siguiente error al ejecutar "yarn start":
![image](https://user-images.githubusercontent.com/42189004/114219190-577d9b80-9938-11eb-8197-4f96ec308a28.png)

 Al parecer no se me instalaron todos los módulos necesarios de koa ya que tuve que instalar manualmente los primeros tres (koa, koa-body y koa-logger) que aparecen en el archivo app.js (Adjunto foto). Nose si me habré saltado algún paso o si hay una forma de instalar todos los módulos necesarios de una (para no hacerlo manualmente para cada uno).  Gracias de antemano, estaré atento a su respuesta.

![image](https://user-images.githubusercontent.com/42189004/114219386-96abec80-9938-11eb-9a2a-c6bd14669402.png)

**Comment by ibaeza1** [comment]
Hola! Como los instalaste a mano? con que comandos?

**Comment by dasolari** [comment]
Hola!
Cuando creas la aplicación después de correr el comando `yo @iic2513/template app-name` te da la opción de instalar las dependencias del proyecto, ¿le pusiste que si? En caso de que le hayas puesto que no, puedes correr el comando `yarn install` para instalar todas las dependencias definidas en el archivo _package.json_.
De todas maneras, esto se verá en detalle en las clases de las próximas semanas.
