### ISSUE TITLE
asociación m:n sequelize

### ISSUE THREAD

**Issue by raimundoloeser** [IIC2513-2021-1/projects#31]
Estamos teniendo un error al agregar elementos a la tabla intermedia. Ya tenemos todo implementado, pero el metodo add (que es el que sale en la documentación) nos tira un error que no sabemos como interpretar. Buscando en internet tampoco encontramos nada util. Quería saber si saben por qué podría ser este error? gracias!

También, ahi aparece como SELECT en vez de INSERT INTO, que también me parece raro.

![image](https://user-images.githubusercontent.com/53836400/116829794-f1211d00-ab73-11eb-9a66-1621f4b4c183.png)

**Comment by meretamal** [comment]
Puedes subir el código del método del router que te está levantando este error?

**Comment by raimundoloeser** [comment]
![image](https://user-images.githubusercontent.com/53836400/116834410-e6728200-ab8b-11eb-89cc-10621e148666.png)


Específicamente en el user.addPost(post), y el resto me funciona ya que lo revise con console.log

**Comment by humbertoortuzar** [comment]
Hola, si no me equivoco el request que quieres hacer debería funcionar así:
`await post.addUser(user)`
Avísame si te funciona!

**Comment by raimundoloeser** [comment]
> Hola, si no me equivoco el request que quieres hacer debería funcionar así:
> `await post.addUser(user)`
> Si no, podrías enviar cómo definiste la relación en los modelos de post y user?

Si lo implemente así, solo que esa fue la ultima forma que traté jajaja de esa manera tambien me genera el mismo error. Aca estan como definí la relacion en post y user

![image](https://user-images.githubusercontent.com/53836400/116841497-6528e880-aba7-11eb-9644-661d0f0b7bf1.png)
![image](https://user-images.githubusercontent.com/53836400/116841513-72de6e00-aba7-11eb-8501-a32c5e245784.png)

Junto con esto, hice la migración para crear la tabla intermedia

**Comment by humbertoortuzar** [comment]
Podrias probar poniendole un "sobrenombre" a la relación, para así llamarla de una distinta manera.
`as: 'sobrenombre',
 through: 'NombreTablaIntermedia',
 foreignKey: {
     name: 'cosaId'
 },`

Luego lo llamas con modelo.addSobrenombre(cosa)

**Comment by raimundoloeser** [comment]
Sigue el mismo problema, lo que yo encuentro raro es que la query sea select y no insert into

**Comment by humbertoortuzar** [comment]
Podrías mandar como estas llamando a esta ruta en la vista?

**Comment by raimundoloeser** [comment]
![image](https://user-images.githubusercontent.com/53836400/116845954-47628000-abb5-11eb-8772-f8643ea65d09.png)

Lo tengo dentro de un form ya que para guardar las publicaciones, tengo que usar un select para indicar el usuario que esta loggeado

**Comment by humbertoortuzar** [comment]
Y en ese form indicas el method='POST' en el form? Si no, creo que toma por default el valor get.

**Comment by raimundoloeser** [comment]
sisi esta con POST, entra bien a la ruta y me carga el user y el post pero cuando hago la asociacion se cae el programa con el error de arriba

**Comment by dhvasquez** [comment]
Hola,una pregunta ¿que es lo que intentas lograr con esa ruta? Porque veo que intentas tener una relación N a N, pero a su vez tienes una relación 1 a N con post y eso puede estar generando confusión

**Comment by raimundoloeser** [comment]
intento crear la asociacion de publicaciones guardadas. Segun yo es es relación N a N, pero también esta la relacion de los users con los post 1 a N, que sería asociar las publicaciones a un dueño

**Comment by sivicencio** [comment]
¿Qué tipo de datos utilizaron para la definición de la tabla intermedia (`UserSavedPosts`)? Pareciera haber un mismatch entre un `integer` y un `uuid`. En el error inicial, se ve que `5` es integer, pero tal vez la comparación falla porque la tabla intermedia usa otro tipo de dato. Debiera ser todo integer.

**Comment by raimundoloeser** [comment]
Claro, debe ser eso, revise la migracion que se me generó y los tiene de tipo uuid, muchas gracias!
