### ISSUE TITLE
ctx.orm retorna undefined

### ISSUE THREAD

**Issue by christianluer** [IIC2513-2021-1/projects#32]
Cuando mi programa corre (ctx.orm.user.find.......)   arroja el problema:
TypeError: Cannot read property 'user' of undefined

La base de datos se creó correctamente desde las migraciones. Al resto del equipo le corre bien esta parte pero a mi me arroja ese problema, intente reseteando todo pero el problema persiste.
Muchas gracias por su atención.

**Comment by meretamal** [comment]
Hola 😁 , puedes subir un ejemplo de código donde esto no les esté funcionando?

**Comment by christianluer** [comment]
`router.param('uid', async (ctx, next) => {
  ctx.state.user = await ctx.orm.user.findByPk(ctx.params.uid);
  if (!ctx.state.user) return ctx.throw(404);
  return next();
})`

**Comment by christianluer** [comment]
es mas que nada el ctx.orm que no reconoce las bases de datos
pero es problema es desde mi ordenador, no pasa lo mismo con los otros teniendo el mismo código y la misma base de datos (migrada de las mismas migraciones)

**Comment by meretamal** [comment]
Tienes alguna rama en tu repo donde pueda revisar tú código?

**Comment by christianluer** [comment]
https://github.com/IIC2513-2021-1/grupo-ethereum-p1/tree/routes se puede entrar desde ahí?

**Comment by meretamal** [comment]
Yap, creo que en el _middleware_ te falta un parámetro. Pásale `(uid, ctx, next)`

Cualquier cosa, te dejo la [documentación](https://github.com/ZijianHe/koa-router#module_koa-router--Router+param)

**Comment by christianluer** [comment]
Muchas gracias era eso!!! un genio ajajaqjajajajajaj saludos.
