### ISSUE TITLE
Error deploy heroku 

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2513-2021-1/projects#33]
Hola, en el deploy de heroku primero salió el error que arreglan en la cápsula, después otro que lo mecionan ahí también de los lockfiles que pudimos arreglar borrando un archivo de `npm` (para sólo usar `yarn`).

Esos ya están resultos pero ahora nos aparece el siguiente error al hacer el push:

![image](https://user-images.githubusercontent.com/62080216/116907392-7c032580-ac0f-11eb-92e4-f8f4f1385bff.png)

**Comment by sivicencio** [comment]
Hola.

El mensaje de error parece indicar que no pudo hacer build de `styles/index.scss`. ¿Se fijaron si los estilos no tienen errores de sintaxis (en todo archivo dentro de `src/assets/styles`)? Si no hay errores, la aplicación debería correr bien en modo desarrollo (`yarn dev`). De lo contrario, deberían ver un error ahí.

**Comment by jirarrazaval** [comment]
Eliminamos en `styles` un atributo de `content: url` que asociaba a una imagen (tuvimos problemas con el template cargándolas desde la carpeta imagenes desde html asique las pusimos con ese atributo en css), y se logró subir a heroku.
El problema es que ahora no se aplica ninguna _stylesheet_, lo que es raro porque al correrla local con `yarn dev` funciona perfecto.

**Comment by sivicencio** [comment]
Al entrar a la aplicación ya arriba en Heroku y analizar su HTML con el inspector del browser, ¿ven dentro de `<head>` un atributo `<link>` con su `href` seteado a algo como `/assets/app-xxxxxxxxxxxxx.css`? Si no lo ven, entonces es porque los estilos no compilaron bien.

Dentro del layout tienen que tener esta línea:
```
<% if (env !== 'development') { %>
  <link rel="stylesheet" href="<%= assetPath('app.css') %>">
<% } %>
```

Si no, nunca se van a incluir los estilos al subirlo a Heroku.
