### ISSUE TITLE
Uso de rutas en un layout

### ISSUE THREAD

**Issue by nicoguz** [IIC2513-2021-1/projects#34]
Hola!
Estoy tratando de poner 'links' con las rutas que definí para los distintos recursos en un layout, pero no encuentro en ningún lado como hacerlo. Como el layout no tiene un controlador (pues se renderea en todas las vistas) no se como 'pasarle' el url a los controladores. Algún consejo?

**Comment by sivicencio** [comment]
Hola.

Puedes revisar los ejemplos en el repositorio oficial de `koa-ejs`: https://github.com/koajs/ejs/tree/master/example

Como hint, fíjate en el uso que hacen de `ctx.state`.
