### ISSUE TITLE
Error heroku seeds

### ISSUE THREAD

**Issue by tlagosh** [IIC2513-2021-1/projects#38]
Hola! pudimos hacer el deploy a Heroku correctamente, nos salieron errores ya resueltos en otras issues y pudimos resolverlo. El problema es que luego, al intentar correr las seeds en heroku, nos sale un error que no sabemos como solucionar.

Corrimos el comando `heroku run yarn sequelize db:seed:all` y nos sale el siguiente error:

![image](https://user-images.githubusercontent.com/53799304/117059400-c529a700-aced-11eb-8818-e6eae45fb94f.png)

No sabemos bien como arreglarlo, gracias de antemano por cualquier ayuda.

**Comment by meretamal** [comment]
Hola 😁 , según lo que vi, dentro de su _seed_ de usuarios tienen esta línea

```js
const { TRUE } = require("node-sass");
```

Bórrenla y hagan el _push_ de nuevo

**Comment by tlagosh** [comment]
Eso lo solucionaba! Muchas gracias!!
