### ISSUE TITLE
Error Unable to connect to the database: ConnectionRefusedError

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2513-2021-1/projects#39]
Hola! Al seguir los pasos de la capsula 5 aún me tira el siguiente error
![Captura de pantalla (913)](https://user-images.githubusercontent.com/62029138/117501008-7711df00-af4b-11eb-906e-4154e8426bb6.png)
![Captura de pantalla (914)](https://user-images.githubusercontent.com/62029138/117501064-901a9000-af4b-11eb-9073-4aba5c10e8ae.png)

Este error ya lo vi en otras issues y también me aparece que mi postgres esta usando el puerto 5433, seguí los pasos que dijeron en #23 de agregar variables de entorno pero el error persiste.Además solo tengo postgres en Ubuntu

![Captura de pantalla (915)](https://user-images.githubusercontent.com/62029138/117501718-70379c00-af4c-11eb-877f-ad811067c9b0.png)
![Captura de pantalla (916)](https://user-images.githubusercontent.com/62029138/117501922-c1e02680-af4c-11eb-91fe-aef4a91a9b43.png)
![Captura de pantalla (917)](https://user-images.githubusercontent.com/62029138/117501932-c4428080-af4c-11eb-8a00-fde7db4ac04b.png)

**Comment by dhvasquez** [comment]
Hola, tu archivo ```.env``` esta en el lugar incorrecto, debería estar al mimo nivel que el directorio ```src``` y tu lo tienes dentro de esa carpeta, el directorio se debería ver de la siguiente manera:
```
MY-PROJECT
|--node_modules
|--src
|   |--assets
|   |--models
|   |--...
|
|--.env
|--package.json
|--...
```

**Comment by RonaldoSosa** [comment]
Corregí eso y ahora me tirá el mismo error solo que en lugar de 5432 dice 5433
![Captura de pantalla (919)](https://user-images.githubusercontent.com/62029138/117512225-391db680-af5d-11eb-97db-25452d1b224a.png)
![Captura de pantalla (920)](https://user-images.githubusercontent.com/62029138/117512259-463aa580-af5d-11eb-92ee-40d0233640ec.png)

**Comment by dhvasquez** [comment]
Y en postgresql de casualidad creaste la base de datos a la que te intentas conectar?

**Comment by christianluer** [comment]
![image](https://user-images.githubusercontent.com/48293211/118744367-3d31ba00-b822-11eb-9d53-0a435fa045f2.png)

Me ocurre un error similar pero con la contraseña, no entiendo porque me la pide y porque no es capaz de funcionar, si anteriormente me funcionaba.

**Comment by Fernan-tess** [comment]
> ![image](https://user-images.githubusercontent.com/48293211/118744367-3d31ba00-b822-11eb-9d53-0a435fa045f2.png)
> 
> Me ocurre un error similar pero con la contraseña, no entiendo porque me la pide y porque no es capaz de funcionar, si anteriormente me funcionaba.

ME PASA LO MISMO

**Comment by Deleon20** [comment]
Hola! 

Un pequeño tip antes de empezar, no se cuelguen de una issue ya resuelta con un problema distinto! Esto hace que sea mas dificil encontrar problemas en las issues para ustedes! 

Ahora creo que deben revisar esta issue #8  :smile:
