### ISSUE TITLE
Error en el primer deploy a Heroku

### ISSUE THREAD

**Issue by jbartolomev** [IIC2513-2021-1/projects#4]
Hola! 
Pudimos crear la app y la subimos al repositorio, pero al crearla en Heroku aparece
`"error: no pg_hba.conf entry"` y no se completa el build. 
Luego agregamos esto a la configuración de producción en database.js:

```js
dialectOptions: {
      ssl: {
        rejectUnauthorized: false
      },
```

Con lo que se completó el build pero vuelve a aparecer el error al abrir la página ("error: no pg_hba.conf entry").

Existe algún paso que me pueda estar saltando? Gracias!!

**Comment by diegoheg** [comment]
Holaa!

Debes primero que todo tener agregado 'Heroku Postgres' en la pestaña de 'Resources' en tu aplicación (Dentro de Heroku).

Si es que ya tienes agregado 'Heroku Postgres', puedes omitir la configuración SSL, que es la que causa el problema, utilizando el comando `heroku config:set PGSSLMODE=no-verify` una vez que están dentro de la Heroku CLI de su aplicación (i.e. en la consola de su computador adentro de la aplicación en Heroku). Alternativamente pueden correr el comando `heroku config:set PGSSLMODE=no-verify -a NombreDeSuApp` para hacerlo directamente desde la consola de su computador sin tener que entrar a la aplicación

Cuéntenme como les va :)

**Comment by jbartolomev** [comment]
Funcionó!! Muchas gracias!
