### ISSUE TITLE
Selected option in form

### ISSUE THREAD

**Issue by Baelfire18** [IIC2513-2021-1/projects#40]
Primero que nada saludos y que esten bien. Como está empezando semana de receso no se si podrán atender mi duda, la hago por si alguno puede.

Básicamente le acabo de agregar a mi modelo de usuario el atributo 'picture', el cúal corresponde a un string asociado al nombre de la foto un avatar a elegir.
A continuacion se puede ver como está en el form:
![image](https://user-images.githubusercontent.com/50716449/117594896-29dd6b00-b10d-11eb-979c-094609271010.png)
Donde `pictures` corresponde a una lista (`const pictures = ['garen_comando.jpg', 'lux.jpg'];`)

Lo que busco hacer es que al haber un error o simplemente al editar esta entidad, este pre selecionada la ultima opción que marqué, tal como sucede con `birth_date`. El caso que esto no sé como hacerlo con este tipo de opcion a elegir en el form.

![image](https://user-images.githubusercontent.com/50716449/117595333-855c2880-b10e-11eb-9d08-ac2a66605058.png)
 Como se puede apreciar por el .css se sabe cuando esta marcado, la cosa es que no puedo hacer que se mantenga la opción marcada con la foto selecionada.

Acá esta mi .css por si acaso aunque no sé si aporte a la solución:
![image](https://user-images.githubusercontent.com/50716449/117595551-1cc17b80-b10f-11eb-96a2-c77ab325dab0.png)

**Comment by sivicencio** [comment]
Los input con `type="radio"` tienen un atributo especial llamado `checked`. Puede ver el detalle en la documentación de MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#htmlattrdefchecked

En pocas palabras, el input cuyo value sea igual a (supongo) `user.picture` debiera tener este atributo seteado (y todo el resto no). Tendrías que ver cómo agregar un atributo HTML de forma condicional al tag input.

Al ver tu código también vi algunas cosas extra, que no tienen que ver con tu pregunta, pero aprovecho de comentarlas:
- Estás usando el mismo id para todos los inputs (`"picture"`). Esto no es buena práctica, pues un id debiese ser utilizado en un solo elemento dentro de un documento HTML
- El div con id `"avatars"` tiene el atributo `selected`. En este caso ese atributo no está agregando nada (probablemente el browser lo ignora)

**Comment by Baelfire18** [comment]
Muchas gracias profesor!!
Ajunto lo que hice por si algún compañero que revise la issue quiera hacer algo similar
![image](https://user-images.githubusercontent.com/50716449/117598962-e0921900-b116-11eb-82a5-9ba6b7829cf2.png)
