### ISSUE TITLE
Error en el objeto error cuando trato de guardar un usuario

### ISSUE THREAD

**Issue by dchahuan** [IIC2513-2021-1/projects#41]
Cuando intento guardar un usuario que no cumple la validaciones puestas me pasa que o la vista me aparece error porque ValidationErrors.errors es undefined y luego cuando intento imprimir los errores para ver porque es undefined me aparece el siguiente error:

TypeError: Expected "id" to be a string

Alguien sabe porque podria ocurrir eso?

Adjunto el codigo en el try catch:

catch (ValidationError) {
    console.log('error');
    console.log(ValidationError);
    await ctx.render('users/new', {
      errors: ValidationError.errors,
      user,
    });
  }

**Comment by sivicencio** [comment]
Probablemente tiene relación con la parte en que guardas al usuario (`user.save(/* ... */)`). ¿Qué le estás pasando como argumento? Pareciera ser que espera algo diferente a lo que le estás pasando.
