### ISSUE TITLE
npm ERR! async not accessible from jake

### ISSUE THREAD

**Issue by christianluer** [IIC2513-2021-1/projects#42]
![image](https://user-images.githubusercontent.com/48293211/118382418-378a6900-b5c3-11eb-8edd-67e4d2266344.png)

En el folder no se tiene node modules, y se esta pusheando a heroku.
Que significa ese problema??
Gracias por su atención

**Comment by Deleon20** [comment]
Hola! 

Vi en su repositorio que borraron el yarn.lock, lo cual puede generar problemas en heroku. Para restablecerla pueden hacer `yarn install`. de hecho como veran en la capsula 6, heroku necesita el archivo **yarn.lock** para instalar las dependencias de su proyecto!

Mucho exito 😃
