### ISSUE TITLE
Unable to connect to the database: ConnectionError 

### ISSUE THREAD

**Issue by Fernan-tess** [IIC2513-2021-1/projects#44]
Hola, tengo un problema, al correr yarn start me aparece el siguiente error
![image](https://user-images.githubusercontent.com/53883016/118981216-1c638480-b948-11eb-983b-64478d1a4797.png)
Antes me funcionaba sin problemas.
**Lo que más me llama la atención es que en postgres no hay ningún usuario "mqfernandez" (ese es el nombre de mi usuario en wsl).** 
En mi archivo .env tengo lo siguiente 
![image](https://user-images.githubusercontent.com/53883016/118981472-5a60a880-b948-11eb-96cb-25ad387d3a46.png)

Ya revisé la #issue39 y #issue8, pero aún no puedo solucionar el problema.

Ayuda, he perdido demasiado tiempo tratando de arreglar este problema y no he podido avanzar en la entrega:(

Sí inicialicé sudo service postgresql start

**Comment by raespinoza4** [comment]
Hola! 

Donde tienes tu archivo .env ? 
Estas utilizando la linea `require("dotenv").config()` para cargar las variables de entorno de tu archivo .env ?
