### ISSUE TITLE
Cannot read property 'findByPk' of undefined

### ISSUE THREAD

**Issue by veneguitas** [IIC2513-2021-1/projects#45]
Hola! Estoy probando el CRUD crear, y me está arrojando el siguiente error al momento de darle ok al boton:
Cannot read property 'findByPk' of undefined
Así está la ruta en donde está 'findByPk':
router.param('id', async (id, ctx, next) => {
  ctx.state.publiacion = await ctx.orm.publicacion.findAll(ctx.params.id);
  if (!ctx.state.publicacion) return ctx.throw(404);
  return next();
});

Busqué cuál podría ser la solución, pero no encontré mucho.

**Comment by sivicencio** [comment]
Hola @veneguitas

Primero en el código que incluiste veo algunas cosas:
- Estás utilizando `.findAll` y pasándole `ctx.params.id`. Debería ser `.findByPk`
- Estás seteando `ctx.state.publiacion` (le falta una `c`). Lo esperable es que entonces siempre te retorne un `404`, pues `ctx.state.publicacion` debería ser `undefined` siempre según lo que se ve en el código (a menos que haya otro middleware que lo setee antes)

Sobre tu duda en particular, ¿es un recurso anidado? Porque si estás creando un recurso **no** anidado, en principio no veo necesario utilizar `.findByPk` (pero puede depender mucho de tu caso). Si es un recurso anidado, sí es necesario, pues tienes que primero encontrar el recurso "padre", y eso seguro viene en la ruta con un id.

En conclusión, creo que falta algo más de contexto del problema que estás intentando resolver. ¿Cómo definiste la ruta para crear?

**Comment by veneguitas** [comment]
Muchas gracias! Ahí arreglé el problema de ctx.state.publiacion, y con respecto a lo otro, nunca me iba a funcionar porque me faltaban otras cosas de antemano, así que en eso estoy ahora.
