### ISSUE TITLE
Editar los modelos 

### ISSUE THREAD

**Issue by veneguitas** [IIC2513-2021-1/projects#46]
Hola! Luego de haber hecho los modelos para la página, me di cuenta de un error que tenía, por ejemplo agregué una ForeignKey a una tabla nada que ver y no a la tabla que correspondía. ¿Cómo puedo editar esto? Prefiero preguntar antes de hacerlo en el mismo archivo jajajajaja

**Comment by dasolari** [comment]
Hola! Cualquier cambio que quieras hacer en tu base de datos debe ser hecho mediante una migración. La migración modificará tu base de datos pero no tu modelo, este debes cambiarlo a mano acorde a lo que modificaste con la migración. El comando para crear una migración vacía es ’yarn sequelize migration:create --name nombre-de-tu-migracion’.

Mucha suerte!

**Comment by veneguitas** [comment]
Muchas graciaaaas <3
