### ISSUE TITLE
Acceder a join table N:N

### ISSUE THREAD

**Issue by raimundoloeser** [IIC2513-2021-1/projects#47]
Hola, me esta funcionando bien la asociación N:N siguiendo la documentación de Sequelize pero no especifican como leer despues los datos de la tabla. Porque me pasa que el User tiene Posts asociados (que son los que el crea con asociados de la forma hasMany). Lo que me pasa es que no puedo leer los que estan en la tabla intermedia 'UserSavedPosts' ya que me lee los que estan asociados con el hasMany. El intento que más me hace sentido que no me esta funcionando es:

![image](https://user-images.githubusercontent.com/53836400/119205548-7eb2a700-ba66-11eb-91ae-940344a0140c.png)

Y no me tira error, sino que es como si no leyera el through.

Gracias!

**Comment by Deleon20** [comment]
Hola!

No estoy muy seguro de como esta modelado en tu archivo **src/models/user.js** pero usar `user.getPosts({through: 'UserSavedPosts'})` deberia ser redudante puesto que en **src/models/user.js** ya esta definida la asociación, entonces   `user.getPosts()` deberia ser suficiente! 

Tambien te recomiendo que revises este [link](https://sequelize.org/master/manual/eager-loading.html) donde hablan de como leer los datos de la tabla en mas detalle!

Mucha suerte! 😄

**Comment by raimundoloeser** [comment]
A eso es lo que me refiero con mi error, que con user.getPosts me accede a los que estan relacionados con hasMany (que especificamente son los que ha creado ese usuario) entonces traté haciendo eso para diferenciar la tabla a la que tenia que acceder. Pero aún asi me lee los que estan en Posts asociados a este user

**Comment by Deleon20** [comment]
Disculpa parece que entendi mal! Pero en ese caso estas haciendo mal el query! 

El modelo **Post** esta asociado al usuario en una relacion **1:N**, por lo que hacer `user.getPosts() ` solo te dara la asociación que tiene en la tabla **Post** (buscara en base al `user_id` que hay en **Post**).

Te recomiendo entonces que apliques la query en la tabla que realmente define los posts guardados (`UserSavedPosts`) y veas en el link sobre el metodo `include` en las queries!

Espero te sirva! 😄

**Comment by raimundoloeser** [comment]
Llevo harto tiempo tratando y realmente no encuentro algo que solucione mi problema. Una de las cosas que hice fue no crear un modelo nuevo (ya que no lo veo necesario para juntar el id del user con id del post sin agregarle mas atributos). E incluso en sequelize dan esas 2 posibilidades, pero en el link todos trabajan con un modelo.

Entiendo que tengo que hacer la query en la tabla intermedia, pero no he logrado encontrar cómo ya que siempre me accede a la de Posts debido a la asociacion de HasMany que tiene el user son los posts

**Comment by raimundoloeser** [comment]
Acabo de lograr que me funcione cambiando las asociaciones de lugar
![image](https://user-images.githubusercontent.com/53836400/119241789-22638c00-bb27-11eb-8b20-ea5886c3e5ad.png)

Pero ya no me deja acceder a los que estan asociados mediante la tabla Posts
