### ISSUE TITLE
Error al cerrar sesión

### ISSUE THREAD

**Issue by jirarrazaval** [IIC2513-2021-1/projects#48]
Hola!

Haciendo la cápsula de manejo de usuarios todo ha funcionado súper bien excepto al apretar el botón de Cerrar sesión. Aparece este error, que no se de dónde puede ser porque está el código de destroy igual a lo que se hace en la cápsula.

![image](https://user-images.githubusercontent.com/62080216/119236641-9477a900-bb06-11eb-806a-a2a12a43ddb6.png)

**Comment by dhvasquez** [comment]
Hola, por lo que veo, al cerrar sesión estas haciendo un llamado POST, mientras que en la capsula de inicio de sesión se utiliza un endpoint tipo DELETE, y si lo seguiste exactamente igual probablemente tambien tienes un endpoint delete, talvez en tu archivo ejs de cierre de sesión te falto el ```input type="hidden"```, para sobrescribir el método post!

**Comment by jirarrazaval** [comment]
Sí tengo el DELETE y el hidden

En `routes/session.js`
![image](https://user-images.githubusercontent.com/62080216/119291458-743a0e00-bc1c-11eb-86a1-b83bcb0a0747.png)

Y en el `html.ejs`
![image](https://user-images.githubusercontent.com/62080216/119291512-90d64600-bc1c-11eb-8bad-8f22cc00946a.png)

Adjunto también lo que tengo de cerrar sesión en `routes.js`
![image](https://user-images.githubusercontent.com/62080216/119291560-a8153380-bc1c-11eb-82ab-615a447b21b9.png)

**Comment by dhvasquez** [comment]
Ahí esta mal el input name, debería ser:
```<input type="hidden" name="_method" value="delete">```
básicamente a method le falto anteponer _, voy a revisar la cápsula a ver que paso.

Saludos!

**Comment by jirarrazaval** [comment]
¡Era eso del method, muchas gracias ahí funcionó!

OK gracias por avisar de las identaciones :)
