### ISSUE TITLE
Hora límite Entrega 1.0

### ISSUE THREAD

**Issue by Tomas-Ira** [IIC2513-2021-1/projects#5]
Hola, una duda la entrega es el jueves 15 a las 23.59? (En el enunciado sale fecha pero no horario)

**Comment by B-Dominguez** [comment]
Hola Tomás. Efectivamente, para la entrega 1.0 tienen todo el día jueves 15 como plazo para subirla. Esto es, hasta las 23:59:59. Teniendo ese plazo para subirla, podrán juntarse dentro de los días siguientes para revisarla junto a su ayudante de seguimiento, según coordinen.

Saludos!
