### ISSUE TITLE
Librerías

### ISSUE THREAD

**Issue by Witomi** [IIC2513-2021-1/projects#51]
Hola!

Quería preguntar si es que hay algún grupo de librerías que sí se pueden ocupar para el proyecto, pregunto ya que quería implementar la expiración se sesión pasado un cierto tiempo, y al parecer hay librerías con las que se puede hacer eso, asi que quizás hay algunas más que están permitidas usar.

Específicamente hablo de koa-session.

Muchas gracias y saludos!

**Comment by dhvasquez** [comment]
La razon por la que no listamos librerias permitidas es porque son muchas y tampoco es facil cubrir todas las necesidades.

Con respecto a koa-session, no solo SI se puede usar, sino que ya viene instalada, y se muestra en la capsula de inicio de sesion como usarse (y ya viene configurada en el proyecto para usarse y con una expiración de 14 días).

Saludos!
