### ISSUE TITLE
Error con routes

### ISSUE THREAD

**Issue by Witomi** [IIC2513-2021-1/projects#52]
Hola!

Dentro de routes.js tengo definido un router.use, mi problema es que cuando le aplico ctx.redirect(ctx.router.url('session.destroy')) en el servidor me aparece que se hace una solicitud de get a /session en vez de un post y termina apareciendome una página del tipo not found, no entiendo porqué no se mete al controlador de session.destroy.

Muchas gracias!

**Comment by dhvasquez** [comment]
Porque redirect solo trabaja con endpoints tipo GET, ya que es una redireccion, no un llamado HTTP.

Saludos!

**Comment by Witomi** [comment]
Gracias!!!
