### ISSUE TITLE
[ERROR] ECCONREFUSED 🆘 

### ISSUE THREAD

**Issue by Ignaciomendezp** [IIC2513-2021-1/projects#54]
Hola! Estoy teniendo problemas al migrar la base de datos. Adjunto imagen del error.
Clone el repo de nuevo, hice yarn install, probe con cambiar la database del .env y nada resulta (a mi grupo si). 
![image](https://user-images.githubusercontent.com/48481728/119277426-a2542980-bbed-11eb-907d-d3ebcf45751f.png)

**Comment by Pablok98** [comment]
Hola, no soy ayudante pero corriste el servidor de postgresql antes? Necesita estar prendido para hacer las migraciones.

**Comment by Ignaciomendezp** [comment]
A que te refieres? Este es mis postgres
![image](https://user-images.githubusercontent.com/48481728/119277944-69698400-bbf0-11eb-90de-65e3ccec6e66.png)

**Comment by Baelfire18** [comment]
@Ignaciomendezp  De casualidad comentaste algo en las migraciones o seeds? Algo como sequelize o interquery? Ya sea del up o del down?

**Comment by Ignaciomendezp** [comment]
Nada, he vuelto a descargar el repo de nuevo. Eso si, al descargar el repo de nuevo tengo que hacer estos pasos (antes no me pasaba):
1. `yarn sequelize db:migrate`
![image](https://user-images.githubusercontent.com/48481728/119278634-76887200-bbf4-11eb-9d60-1f3fb3320f3d.png)
2. `sequelize init`
![image](https://user-images.githubusercontent.com/48481728/119278665-a899d400-bbf4-11eb-9fc5-89ac00b3ff75.png)
3. `yarn sequelize db:migrate`
![image](https://user-images.githubusercontent.com/48481728/119278670-b3ecff80-bbf4-11eb-81d4-a39109a59e6c.png)
4. `npm install mysq12`
![image](https://user-images.githubusercontent.com/48481728/119278691-d67f1880-bbf4-11eb-8616-227cd01d5a3e.png)
5. `yarn sequelize db:migrate`
![image](https://user-images.githubusercontent.com/48481728/119278698-e72f8e80-bbf4-11eb-86c7-7418526b144d.png)

**Comment by Baelfire18** [comment]
Imep (por Tony por si acaso no un ayudante jaja), cuando lo vuelves a descargar creas el `.env` siempre cierto?

**Comment by Ignaciomendezp** [comment]
Wena, si, lo creo siempre

**Comment by dhvasquez** [comment]
Hola, primero que no debiste correr ```sequelize init``` porque sobreescribes ciertos archivos importantes, segundo estas instalando ```mysq12```, y para el proyecto utiliamos PostgreSQL, no mySQL. Una pregunta el archvio .sequelizerc en tu carpeta raiz que tiene? (puede que se haya corrompido, pues sequelize esta buscando un archivo que no debiese existir).

**Comment by Ignaciomendezp** [comment]
Creo que no tengo ninguna carpeta `.sequelizerc`, incluso realize el set up de nuevo.

**Comment by dhvasquez** [comment]
Ya nose porque no los tienes pero es importante que exista, por eso no sabe donde conectarse sequelize, es imporatnte que en la raíz exista ```.sequelizerc``` y su contenido sea **exactamente**:
```
const path = require('path');

module.exports = {
  config: path.resolve('src', 'config', 'database.js'),
  'migrations-path': path.resolve('src', 'migrations'),
  'models-path': path.resolve('src', 'models'),
  'seeders-path': path.resolve('src', 'seeds'),
};
```

**Comment by Ignaciomendezp** [comment]
No solo me faltaba ese archivo, me faltaban todos los ocultos, cree un template nuevo, y copie y pegue los archivos ocultos de esa app a la nuestra. Gracias @dasolari y a los otros ayudantes que ayudaron  🙌🏼  🙌🏼  🙌🏼
