### ISSUE TITLE
Error Amazon web server

### ISSUE THREAD

**Issue by pedroherreraj** [IIC2513-2021-1/projects#59]
Hola! Estoy utilizando amazon web server para poder hacer la funcionalidad de que los usuarios puedan subir achivos a la página, y me está tirando el siguiente error. Por qué podríar ser? Ya puse mi clave de aws en la app

![Captura de Pantalla 2021-05-25 a la(s) 15 38 13](https://user-images.githubusercontent.com/62112123/119558342-47e2d680-bd6f-11eb-831e-d10841f8298c.png)

**Comment by pedroherreraj** [comment]
Ya lo pude arreglar y se me suben las fotos a mi bucket, pero me pasa que al apretar el url de estas, en vez de que se abran en una página, se me descarga. Por qué puede estar pasando esto?

**Comment by dhvasquez** [comment]
Hola, lo cierto es que en este curso no cubrimos AWS, por lo que no es muy apropiada tu issue, pero si te entrega un link de descarga, probablemente estas pidiendo el link inapropiado, y deberias buscar aquel url publico que entregan los buckets.
