### ISSUE TITLE
Podemos utilizar react?

### ISSUE THREAD

**Issue by perezpefaur** [IIC2513-2021-1/projects#6]
Mi pregunta nace ya que react es altamente utilizado dentro de el desarrollo web, por lo que hay una mejor comunidad de personas para aprender. 

Gracias!

**Comment by Deleon20** [comment]
Hola!

Para el proyecto 1 el objetivo es hace una pagina tradicional, por lo que no esta permitido usar React, incluso si el template lo incorpora.

**Comment by sivicencio** [comment]
Complementando la respuesta de @Deleon20, en el Proyecto 2 tendrán que utilizar React, así que de todas maneras es algo que aprenderán en el curso. El Proyecto 1 los preparará para poder desarrollar el Proyecto 2 (es probable que varias cosas les hagan sentido en ese momento gracias al Proyecto 1).
