### ISSUE TITLE
Entrypoint app = app.js

### ISSUE THREAD

**Issue by Baelfire18** [IIC2513-2021-1/projects#60]
Hola me esta fallando esto  y no sé porque. Borre la carpeta y la volvi a descargar (creando el .env y corriendo el ``yarn install`) y me sigue fallando. No sé que hacer!
![image](https://user-images.githubusercontent.com/50716449/119579400-4c69b800-bd8c-11eb-9274-db798f76da16.png)
![image](https://user-images.githubusercontent.com/50716449/119578093-e3814080-bd89-11eb-9a98-43d962f15562.png)

**Comment by sivicencio** [comment]
Hola. No entiendo cuál es el error. En principio veo todo bien en el output de `yarn dev`.

**Comment by humbertoortuzar** [comment]
Hola! Se arreglo reiniciando el PC
Saludos
