### ISSUE TITLE
Error deploy de heroku

### ISSUE THREAD

**Issue by jordonezp** [IIC2513-2021-1/projects#61]
Hola. Estamos tieniendo un error al hacer deploy heroku. No está reconociendo el modulo `webpack` por alguna razón. El build se está pudiendo completar con exito, pero al intentar acceder a la web app dice que hay un erorr. Adjunto imagenes de la consola y del navegador.

El build se realiza con éxito.
![photo_2021-05-26_10-38-59](https://user-images.githubusercontent.com/53804102/119679782-a14e1280-be0e-11eb-9cb2-a98a4a6fc6af.jpg)

Sin embargo, no se puede acceder a la aplicación.
![photo_2021-05-26_10-38-55](https://user-images.githubusercontent.com/53804102/119679781-a14e1280-be0e-11eb-8eac-8af5c8402b3b.jpg)

Al correr `heroku logs --tail` menciona un error con el módulo webpack
![photo_2021-05-26_10-38-52](https://user-images.githubusercontent.com/53804102/119679779-a0b57c00-be0e-11eb-8bfe-29201fe4154b.jpg)

Pero el módulo está en el proyecto
![photo_2021-05-26_10-38-45](https://user-images.githubusercontent.com/53804102/119679774-a01ce580-be0e-11eb-9736-94ac27492cd0.jpg)

**Nota:** La aplicación está funcionando a la perfección en local y corri yarn install justo antes de hacer el deploy.

Por favor ayuda para solucionar esto. De antemano muchas gracias!

**Comment by humbertoortuzar** [comment]
Si no me equivoco, en esta issue tuvieron este mismo problema y adjuntaron un link que les ayudó:

#36

**Comment by humbertoortuzar** [comment]
Por otro lado, podrías mandar una foto de las primeras líneas de `/app/src/routes/publications.js`?

**Comment by milosoria** [comment]
Hola, logramos arreglar el problema. En algun  momento cambiamos, sin darnos cuenta, la version de webpack en el yarn lock. Con `yarn remove webpack && yarn add webpack@4.44.1` se arreglaron los problemas cons sus peer dependencies. Gracias de todas formas!
