### ISSUE TITLE
Error al abrir Visual Code Studio

### ISSUE THREAD

**Issue by mafernandez9** [IIC2513-2021-1/projects#64]
Hola! Durante la semana pasada, mi computador presentó un problema (pantallazo azul, cuyo error no alcancé a registrar) y tuve que utilizar una especie de checkpoint del día anterior. 
Desde este problema, mi computador ha presentado distintos problemas al momento de iniciar ciertos programas. Cuando intenté correr wsl, y moverme a linux con 'cd ~/nombre_repositorio' no hubo ningún problema (de hecho, puedo hasta correr la aplicación de la entrega pasada con yarn), Sin embargo, al momento de correr el comando 'code .' para poder abrir el editor de código, se queda pegado sin hacer nada. 
Luego,  intenté ver si tenía los packages con 'sudo apt install code' y me lanza el siguiente error: "E: Unable to locate package code", y no puedo trabajar con la wsl si no puedo abrir mi carpeta de linux con code. Cabe destacar que trabajo con Windows. 
Si pudiesen ayudarme, lo agradecería mucho. ¡Saludos!
PD: Si necesitan un pantallazo o algo, lo adjuntaré.

**Comment by humbertoortuzar** [comment]
Hola! Puedes intentar por mientras una forma paralela.
Abres Visual Studio Code en windows, y aprietas la esquina de abajo a la izquierda (open a remote window): 
![image](https://user-images.githubusercontent.com/53840891/120952868-e0873800-c719-11eb-900a-fce11351410b.png)

Luego seleccionas "New WSL Window" y te debería abrir una nueva ventana en WSL, ahi pones "open folder" y abres la carpeta que quieras usar.
Avísame si te funciona!

**Comment by mafernandez9** [comment]
Hola! Intenté lo que me dijiste, pero lleva cerca de 10 minutos y no se ven los archivos ni nada. Adjunto foto de lo que me sale:
![imagen](https://user-images.githubusercontent.com/53874019/120954484-504af200-c71d-11eb-8088-2f5faa558761.png)

Muchas gracias!

**Comment by humbertoortuzar** [comment]
No pude encontrar soluciones muy esperanzadoras jajaja
Parece que la forma más simple es volver a instalar wsl.

Por otro lado, quizás estas issues puedan ayudarte:

https://github.com/microsoft/vscode-remote-release/issues/3745

https://github.com/microsoft/vscode/issues/107485

**Comment by humbertoortuzar** [comment]
Otra opción que tienes es intentar reinstalando la extensión de wsl en VSCode, aquí mencionan que les funcionó:

https://github.com/microsoft/vscode-remote-release/issues/1972

**Comment by Deleon20** [comment]
Complementando un poco la respuesta de @humbertoortuzar, los pantallazos azules se deben a errores de caracter critico en Windows, se relacionan con inestabilidades de hardware o errores en windows como tal, que hacen que el sistema **crashee** antes de corromper datos. Sin embargo no es un sistema perfecto y por ende puede causar una corrupción de datos, por lo que si tienes problemas despues de un pantallazo azul, lo mejor es reinstalar los programas que presenten problemas!

**Comment by mafernandez9** [comment]
Entiendo, entonces la mejor opción sería reinstalar wsl. Mi preocupación sería que mañana es la Interrogación 1, nos pedirán ocupar Node.js? pregunto para saber si necesito instalar todo desde hoy. Muchas gracias!
