### ISSUE TITLE
Interrogación 1

### ISSUE THREAD

**Issue by veneguitas** [IIC2513-2021-1/projects#65]
Hola! Aparecen los archivos de la interrogación, pero no se puede acceder a ellos, me tira "acceso denegado". Saludos!

**Comment by B-Dominguez** [comment]
Hola Valentina,

Como contesté en el correo, al parecer es un error de Canvas porque en ambas secciones pasó lo mismo (no se desbloqueó el módulo según la hora programada). Ya fue arreglado en ambas, en el caso de la S2 hace unos minutos (creo que al minuto de hacer la _issue,_ estaba arreglado hace poco), lo siento por el inconveniente y muchas gracias por avisar!

Saludos

**Comment by veneguitas** [comment]
Muchas gracias!
