### ISSUE TITLE
[I1] Pregunta D

### ISSUE THREAD

**Issue by vchauriye** [IIC2513-2021-1/projects#69]
Hola, en la pregunta D debe existir un manejo de errores? Por ejemplo, si es que las dos cadenas de ADN fueran de largos disttintos, o si es que lso strings ingresados no fueran cadenas de ADN.

**Comment by josefeliuf** [comment]
Tengo la misma duda! debemos asumir que los largos de original y final string siempre son iguales? ya que dice "Una mutación se define como una letra no coincidente en finalString, comparado con la **misma ubicación** en originalString" por lo que si final string tiene mayor largo, esa posicion no existiría en original

**Comment by sivicencio** [comment]
Hola @vchauriye. Pueden suponer que ambas cadenas tendrán el mismo largo, y que sólo tendrán caracteres válidos como secuencias de ADN.

Sólo como dato, esto se vio en la sesión de preguntas por Zoom y probablemente encontrarán la respuesta en el resumen que se subirá prontamente en una issue.
