### ISSUE TITLE
Intalacion de capsula 2

### ISSUE THREAD

**Issue by Baelfire18** [IIC2513-2021-1/projects#7]
![image](https://user-images.githubusercontent.com/50716449/115622459-de7e2c80-a2c5-11eb-8c47-74833f645860.png)
Hola llevaba todos los pasos de instalacion del video de la capsula 2. Pero al intentar cambiar de koa de `npm` al de `yarn` me tiro este error al instalar este ultimo.
No se como arreglarlo

**Comment by B-Dominguez** [comment]
Hola @Baelfire18 . Leyendo los mensajes en consola, el problema que tienes no es con yarn, sino con Node, que no ha sido instalado. En el mejor de los casos, no reiniciaste la consola después de instalar Node. Si no es solo eso, muestra por favor los pasos que has seguido para la instalación de Node y sus resultados, para poder ayudarte mejor

**Comment by Baelfire18** [comment]
Creo haber seguido la instalciuon correcta de node. Eso si tuve un problema al principio pq tenia otra version pero se supone la cambie. Ajunto foto de lo que tengo ahora como versionde node. 
Tampoco entiendo pq me dice version 4.0 y yo tengo v16. Son como otras escalas?

![image](https://user-images.githubusercontent.com/50716449/115625685-69f9bc80-a2ca-11eb-8dce-f1bbb1e63300.png)

**Comment by B-Dominguez** [comment]
Puedes correr 'node -v' y 'nodejs-v'?
Ojo que las v son en minúscula, por eso te arrojó bad options

**Comment by Baelfire18** [comment]
Deberia instalar `nodejs` con el comando dado en consola?
![image](https://user-images.githubusercontent.com/50716449/115626798-feb0ea00-a2cb-11eb-837b-c97a55b8251a.png)

**Comment by B-Dominguez** [comment]
Ok no, pero haz lo siguiente, como explica la documentación referenciada:
![image](https://user-images.githubusercontent.com/26129405/115628495-b7782880-a2ce-11eb-8a68-0171d78b1362.png)


Si eso no funciona, confírmame por favor tu versión de Ubuntu y el listado de pasos que seguiste para instalar yarn. Debería ser algo así como

- sudo apt remove cmdtest
- sudo apt remove yarn (si lo trataste de instalar de otra forma)
- rm -rf ~/.yarn (si lo trataste de instalar de otra forma)
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
- sudo apt update && sudo apt install --no-install-recommends yarn
- Setear paths en .bashrc
- reiniciar tu consola

Ojo que el flag --no-install-recommends es importante

**Comment by dhvasquez** [comment]
Hola, sumando a lo que dijo Benjamín, antes de instalar ```yarn```, mejor formaliza tu version de Node, ya que no vamos a usar la version 16, sino la version 12.X (la penúltima versión de node LTS). Con ```nvm``` puedes elegir la versión, con que eligas la version 12 deberia instalarse tanto node y npm.

Luego te recomiendo hacer los primeros 2 pasos:
- sudo apt remove cmdtest
- sudo apt remove yarn (si lo trataste de instalar de otra forma)
- rm -rf ~/.yarn (si lo trataste de instalar de otra forma)

Sin embargo, desde aquí primero deberías verificar que tienes la versión correcta de node:  
input: ```node --version```, output: ```v12.13.0```  
Y verificar que tienes la versión de npm con la que viene dicha versión:  
input: ```npm --version```, output: ```6.12.0```  

Una vez tengas tanto Node, como NodePackageManger instalados, recomiendo instalar yarn de la siguiente forma:  
```npm install --global yarn```  
ya que es la forma que ahora se esta utilizando (en vez de la anera por repo como mencionó Benajmín, aunque cualquiera de las 2 funciona.

**Comment by Baelfire18** [comment]
Muchas gracias por la ayuda a ambos.
Eso si no pude cambiar mi version de node como me dijiste debido a no tener algo de pyhon al parece
![image](https://user-images.githubusercontent.com/50716449/115636979-2492ba80-a2dd-11eb-99fb-1f1762ec2d01.png) (@dhvasquez )

Y con respecto a lo de `yarn` que decias @B-Dominguez , no se como setear paths en .bashrc

**Comment by dhvasquez** [comment]
Hola,

Primero, la version de node 12.4 no existe, es la version 12.13.0 la mas reciente de la versión 12 (de hecho puedes elegir ```nvm use 12``` y debería funcionar).

Segundo, si lo instalas con npm (```npm install --global yarn```) no debiese pedirte setear variables de entorno

**Comment by B-Dominguez** [comment]
Me sumo al consejo de Diego en el sentido de que efectivamente ahora la instalación de yarn mediante npm debería funcionar bien, y es ahora de hecho planteada en la documentación referenciada en la cápsula.

Ahora bien, para la instalación de la versión de node que requiere el template, como se explica en la cápsula y bien plantea Diego, puedes usar el alias '12' para instalar la última versión estable de node 12.X ( <code>nvm install 12</code> al instalarlo). Además, puedes setear esa versión como default con <code>nvm alias default 12</code>

De todas formas, ojo que el problema que tuviste ahí es con la caché de nvm, y se debería poder solucionar con:

 <code>nvm cache clear</code>
 
 Sobre setear los paths, si de todas formas te interesa, se explica en la cápsula y se hace agregándolos en el archivo ~/.bashrc, que puedes entrar a edita, por ejemplo,r con:
 
 <code>sudo nano ~/.bashrc</code>
 
 Al final del archivo, es donde deberías haber tenido seteado los paths que se muestran en cápsula y documentación, y donde podrías haber agregado:
 
 <pre>alias nodejs=node</pre>

**Comment by Baelfire18** [comment]
![image](https://user-images.githubusercontent.com/50716449/115650786-ef479600-a2f7-11eb-80ac-c90ab77c33d7.png)
He intentado de reiteradas formas, intentando desinstall `nvm` y volviendo a ponerlo pero no puedo descargar la version de node `12.22.1`

**Comment by B-Dominguez** [comment]
Prueba con:
`nvm list`

Para cada versión 12.X que te aparezca:
`nvm uninstall 12.X`

Luego:
`nvm cache clear`
`nvm install 12`
