### ISSUE TITLE
[I1] Pregunta G

### ISSUE THREAD

**Issue by fivaldivia** [IIC2513-2021-1/projects#70]
Hola, cómo están? Fui a la sesión de ayuda pero no escuche si preguntaron algo como esto por lo que lo dejo acá: Quería saber si el arreglo **freq** que nos entregan es de las frecuencias del texto encriptado y al final yo tengo que compararlo con la tabla de frecuencia de letras para el idioma español que nos dan en el enunciado para traducir el texto? 
Muchas gracias!

**Comment by sivicencio** [comment]
Hola @fivaldivia. El arreglo `FREQ` (en el proyecto lo verás con mayúsculas) corresponde a la tabla de frecuencias del idioma español. Tiene leves diferencias con la imagen porque fue adaptada para el problema.

Deben utilizar la tabla de frecuencias `FREQ` para comparar las frecuencias de letras en el texto de prueba.
