### ISSUE TITLE
[I1] Pregunta B/C

### ISSUE THREAD

**Issue by nicoguz** [IIC2513-2021-1/projects#71]
Hola!
Los botones deben realizar alguna acción al presionarlos??

**Comment by dasolari** [comment]
Hola!
No debe redireccionar a ningún lado, si a eso te refieres con acción, pero si debe notarse que es un botón al hacerle click (en cuanto a _hovers_, tamaño, color, estilos en general).

**Comment by nicoguz** [comment]
Perfecto, gracias!!
