### ISSUE TITLE
[I1] Pregunta B/C

### ISSUE THREAD

**Issue by vapina** [IIC2513-2021-1/projects#72]
Las fotos pueden no estar representadas por una x y poner fotos reales por ejemplo?

**Comment by dasolari** [comment]
Hola!
En cuanto a las imágenes, en la X va una imagen cualquiera. Recomendamos que las descarguen y las incluyan en su carpeta `src` de la forma que quieran, lo importante es que este __DENTRO__ de `src` (una imagen copiada de Google no les asegura que siga disponible cuando se les corrija) y fijarse en el tamaño de la foto (que no sea pesada).
