### ISSUE TITLE
[I1] Pregunta E

### ISSUE THREAD

**Issue by totichi** [IIC2513-2021-1/projects#74]
Hola!
Quería preguntar si la función itemsByBranch debe retornar un array con objetos nuevos, o si basta con que retorne un array que contenga los objetos que cumplen la condición, pero que esten referenciados al array incial.

**Comment by sivicencio** [comment]
Hola @totichi. Debe ser un array (objeto) nuevo. Esta parte del enunciado lo indica:
> Nota: No deberán alterar el contenido del objeto Store, sino que el retorno deberá ser otro objeto.
