### ISSUE TITLE
[I1] Pregunta G

### ISSUE THREAD

**Issue by bpardobravo** [IIC2513-2021-1/projects#76]
Hola, tengo una duda sobre lo que se pide.
Digamos que una letra es la N°10 más usada en el texto encriptado. ¿La solución pide mapearla con la décima más usada del arreglo FREQ, o con la que más se asemeje en porcentaje de uso?
Si entendí bien, estas 2 opciones podrían dar resultados distintos ya que hay letras que no se usan en el texto encriptado.

**Comment by Deleon20** [comment]
Hola!

Esto es parte de lo que se pide como metodo de desencriptación, ya que no puedes comparar porcentajes exactos, debes desarrollar un metodo de asignación de letras. El unico criterio importante para validar si tu metodo es correcto es que sea legible por un humano.

Mucha suerte!
