### ISSUE TITLE
[I1] Pregunta B [footer]

### ISSUE THREAD

**Issue by mpmunoz13** [IIC2513-2021-1/projects#77]
Hola, 
Es necesario que el footer se mantenga pegado al final de la página? puede estar al final del contenido o es necesario que el footer me "acompañe" al final de la pagina cuando hago scroll?

**Comment by Deleon20** [comment]
Hola!

No es muy comun que las paginas usen _sticky_ footer entonces no es necesario que el footer sea _sticky_ (que te "acompañe" mientras haces scroll)!
