### ISSUE TITLE
Pregunta B/C

### ISSUE THREAD

**Issue by Mjtala** [IIC2513-2021-1/projects#78]
Hola! Tengo una duda en relación a este comentario
"Toda el área de su diseño debe estar centrado en el browser (en elwireframe, elárea visible del browser está representado de un tono gris), debe tener un color distinto al default del browser (en este caso pusimos celeste), y no debe ocupar todo el ancho de la pantalla." 
No entiendo si literal tengo que hacer mi página más chica que el total del computador o simplemente centrar el contenido.
Estaría bien lo de la foto?
![interrogacion](https://user-images.githubusercontent.com/62020259/121246320-0d992f00-c86f-11eb-8b56-a1261c694537.PNG)

**Comment by Deleon20** [comment]
Hola!

Debes centrar el contenido en tu browser **y** ademas hacer que estos elementos no usen todo el ancho de la pantalla ( osea en el ejemplo que pusiste los elementos deben tener espacio gris a ambos lados). En otras palabras tienes que hacer que tus elementos no usen la toda tu pantalla de lado a lado y deben estar centrados

Saludos!

**Comment by Tomas-Ira** [comment]
Hola perdón, no entendí, el fondo no puede llegar hasta el borde o los elementos de la pagina. En otras palabras, el lado izquierdo de la foto de arriba ¿Está bien?

Gracias de antemano!

**Comment by sivicencio** [comment]
En los wireframes hay una caja que encierra todo el contenido, de color celeste. Es esta caja la que no debe llegar hasta el borde y que debe estar centrada. En la foto no se alcanza a ver si hay algo fuera de lo celeste de otro color, por lo que no podría responder en base a ella.
