### ISSUE TITLE
[I1] Pregunta H

### ISSUE THREAD

**Issue by matioprts** [IIC2513-2021-1/projects#80]
Hola, respecto a la pregunta H me surgieron unas dudas:

1. Cuando en el enunciado indican "arrojar un error" y "retornar el error" ¿ambos casos se refieren a literal implementar un error y su manejo en el código, o el primero es arrojar y manejar error y el segundo es retornar el error como un valor resultado de la función simplemente?
2. splitSample() dice que puede fallar, sin embargo no se indica el código asociado ni en qué situación falla ¿es necesario implementar esa lógica?
3. en la función applyTestC() indica "se retorna el código XXX y el mensaje XXX" según la situación ¿esperan que retorne ambas, que retorne el numero y haga log en la consola del mensaje, que arroje un error?

**Comment by HernanCabrera** [comment]
Hola, en realidad el manejo de errores es importante que lo implementen en los casos expuestos. "arroja o retorna" estan tomados en su sentido amplio, en el fondo deben, por enunciado ver el tratamiento a errores de tipo "terminal".
(2) spliSample() puede fallar, es parte de su diseño ver siarroja o no error, es libre, lo importante es que si falla, se interrumpe toda ejecución futura
(3) Si, arroja el error y se hace console.error :)
