### ISSUE TITLE
[I1] Formulario y modificación de respuestas

### ISSUE THREAD

**Issue by milosoria** [IIC2513-2021-1/projects#82]
Hola, tanto en el mail que enviaron como en el form, especificaba que se permitía modificar las respuestas, pero resulta que solo deja modificar el número de alumno y no el zip.

**Comment by B-Dominguez** [comment]
Hola, parece extraño porque sí está configurado para aceptar actualizaciones en la respuesta, pero veré por qué se podría estar presentando el problema.

En cualquier caso, se ofrecerá pronto una solución para poder actualizar el archivo entregado, para que puedas estar tranquilo por ese lado

**Comment by B-Dominguez** [comment]
Ok, aparentemente es un problema de Google Forms al actualizar archivos adjuntos en una respuesta, por lo que habilité múltiples respuestas de un usuario. Ahora deberías poder volver a responder, y solo se considerará la última versión que envíes. 

@milosoria Avísame por favor por este mismo medio si todavía presentas problemas.

Éxito!

**Comment by milosoria** [comment]
Ahí si!!! Graciass
