### ISSUE TITLE
[I1] Pregunta H

### ISSUE THREAD

**Issue by perezpefaur** [IIC2513-2021-1/projects#83]
Tengo duda en lo siguente:
1. No existe la constante MIN_WEIGHT_D, supongo que lo creamos nosotros?
2. En TEST_ARRAY_RESULTS hay un 0 en la posicion del test C, supongo que deberia ser un 201 o 301?
3. "Ya sea que applyTestC() retorne 999 o applyTestB() se haya aplicado con éxito, se ejecuta la prueba D con applyTestD()." Esto significa que en cualquier caso que testB o testC, haya corrido de forma correcta ejecuto applytestD() o se refiere a que tiene que cumplirse que testC retorne 999 o testB haya corrido bien?

**Comment by sivicencio** [comment]
Hola @perezpefaur, dejo las respuestas a continuación:
1. Es un error, debiese estar `MIN_WEIGHT_D` en vez de `MIN_WEIGHT_C` en las constantes. Puedes cambiarle el nombre para probar (el repositorio fue actualizado, pero no es necesario que le hagas pull si ya lo cambiaste a mano)
2. Puedes modificar `TEST_ARRAY_RESULTS` a gusto. Si consideras que el ejemplo no está bien, entonces prueba con el valor que consideras correcto. El valor del array que se encuentra en el código es más que nada referencial
3. Dejo esta respuesta pendiente por un rato. Habrá un nuevo comentario al respecto.

**Comment by perezpefaur** [comment]
Oka! Perfecto. En relacion a la pregunta 3 tmb esta el siguente ejemplo en la prueba:
[
{ test: ”A”, result: 301 },
{ test: ”B”, result: ”NA” },
{ test: ”C”, result: 999 },
{ test: ”D”, result: ”NA” },
]
Pero no veo como esto seria posible, ya que si C retorno 999 entonces D tendria que tener un codigo: ya sea 901 o el codigo binario.

**Comment by HernanCabrera** [comment]
Para la parte 3 de la pregunta: hay dos caminos para llegar al testD, una desde testB (sin pasar por testB) y otro camino es desde testC sin pasar por testB
Asi pues puedo hacer A->B->D  o puedo hacer A->C->D
la decision de bifurcacion es en TestA donde puedo ir a C y de C a D (o de C a Error)
Espero aclare.

**Comment by HernanCabrera** [comment]
Sobre el retorno, tienes toda la razon, hay un error en el ejemplo, Si pasa C con 999 llego a D El cual o falla con 901 o retorna exito .
toda la razon
