### ISSUE TITLE
[I1] Pregunta G

### ISSUE THREAD

**Issue by mafernandez9** [IIC2513-2021-1/projects#84]
Hola! Tengo una duda. ¿Esta función debe cumplir con algún tipo de importancia por respecto a las letras que más se repiten? Me refiero a que si primero debe priorizarse la letra que más se repite, o si se puede ocupar otro tipo de criterio.

**Comment by HernanCabrera** [comment]
El criterio es la frecuencia con que la letra aparece en el texto encriptado, ese porcentaje despues lo buscas en la tabla de frecuencia y lo aproximas al mas proximo en la tabla de frecuencias entregada.

**Comment by Marialuisaclaro** [comment]
Hola @HernanCabrera! Pero dado que no se pueden repetir las letras para mapear, afecta el orden en que se buscan. Es decir si tengo a:15 b:16 y z:16, y:2, el orden en que se comparen las fecuencias van a determinar el mapeo, en este caso sería a:z b:y vs la otra combinación.

**Comment by Marialuisaclaro** [comment]
Hola @HernanCabrera ! Pero se debe hacer esa busqueda/mapeo partiendo por las letras que tienen mayor frecuencia en el texto encriptado? Dado que no se pueden repetir letras, el orden en que se busca determina mucho la encriptación.

**Comment by mafernandez9** [comment]
Claro, mi duda iba por este lado @Marialuisaclaro. No se si existirá alguna clase de importancia al momento de realizar este mapeo

**Comment by HernanCabrera** [comment]
En rigor ese es parte de tu algoritmo de marching.. tienes que calcular de alguna forma (simple, tampoco hay que matarse) el porcentaje en freq que mas se acerque al que encontraste y luego tienes que tener algun algoitmo de desempates.
por supuesto que letras con procentajes bajos tenderan a quedar intercambiadas y pasará que la frase "yo queria" puede quedar como "qo yueria" si es que la "y" y la "q" están muy próximas.

**Comment by mafernandez9** [comment]
De acuerdo, muchas gracias profesor!

**Comment by HernanCabrera** [comment]
cuando los valores se aproximan muhco es tipico en letras de baja frecuencia de aparición, alli tendrpa que generar algun algoritmo de desempate, pero no se torturen mucho con los de baja frecuencia y elija alguna regla de desempate adecuada, recuerden que el objetivo es poder "leer" medianamente el texto.
Por ejemplo, leer "eska es li kaza" se puede entender como "esta es mi taza".. y es un resultado adecuado.. pero uno no adecuado sería: "emla em ju vaqa" alli ya no se distingue ni se infiere.
