### ISSUE TITLE
i1 [G]

### ISSUE THREAD

**Issue by fjcroquevielle** [IIC2513-2021-1/projects#85]
La frecuencia de las letras podemos asumirla como porcentaje de las veces que aparecen? 
Gracias

**Comment by Deleon20** [comment]
Hola!

No entiendo muy bien que quieres asumir pero la frecuencia de las letras es la cantidad de veces que aparece en el texto, dado en forma porcentual.

Saludos!

**Comment by fjcroquevielle** [comment]
Es que esa era mi pregunta, porque al sumar las frecuencias de las letras (de la estructura FREC) la suma no me da 100.

**Comment by HernanCabrera** [comment]
No te preocupes por eso, hemos reiterado que freq es una tabla de frecuencias ajustada para esta pregunta de tal forma que lo que encuentren en el texto se acerque (depende de sus algoritmos de matching) lo mas posible al texto.  Lo importante es que calcules los porcentjaes de las letras  del texto entregado y lo trates de encontrar en freq y "adivinar" la letra.

**Comment by fjcroquevielle** [comment]
Perfect. Muchas gracias! entonces asumiré que se la frecuencia en realidad es el procentaje (lo que estaba haciendo antes era frecuencia/suma_frecuencias y me daba un poco peor). Gracias!!
Saludos.

**Comment by BelenMadariaga** [comment]
Holaa, sumándome a esto, la frecuencia/porcentaje estaría determinada por (cantidad de apariciones*100)/text.length o hay que quitar los cáracteres de puntuación y la misma í ?

**Comment by HernanCabrera** [comment]
Es relevante lo que dices, dado que los "." y otros, no se enccriptan, es relevantes quitarlos del total de letras :-) pero no le digamos a nadie
