### ISSUE TITLE
Pregunta G Método

### ISSUE THREAD

**Issue by MINGOD24** [IIC2513-2021-1/projects#86]
Hola,

Me surge una duda al realizar la pregunta G. Si yo calculo en orden los porcentajes de ocurrencia en el texto y luego junto el que tuvo el mayor porcentaje con la letra que tiene mayor ocurrencia en el idioma castellano (lista FREQ), y así sucesivamente, esta bien? He visto issues que se contraponen un poco entonces me gustaría saber si es valido este método.

**Comment by HernanCabrera** [comment]
Pues tu te armas tu propia tabla de ocurrencias y sacas los porcentajes relativos por letra, eso está bien y luego por cada frecuencia (o proporcion en realidad) de letra encontrada, buscas el porcentaje que mas se acerqueen la lista freq y eso es tu letra adivinada. <hasta alli lo generico>
Ahora, unas consideraciones:
Claramente no encontrrás porcentajes exactos y tendras que definir algun algorito apropiado de distancias y otro de solución de conflictos cuando tengas porcentajes muy similares que hagan que una letra "encriptada" pueda coincidir en frecuencia con mas de una letra "real".. pero eso es parte de los desafíos de la pregunta.

**Comment by MINGOD24** [comment]
gracias profe por la respuesta. Entonces utulizar el metodo que propuse esta mal? Es decir, esta mal ordenar las ocurrencias del texto y las de freq y juntar la primera con la primera, segunda con segunda y asi sucesivamente?

**Comment by HernanCabrera** [comment]
No está mal, en rigor eso es lo que se hace al "buscar" el coincidente. Lo que le pasará es que como no tienes la misma cantidad de letras en el texto encriptado que en freq (el texto encriptado no tiene todas las letras del alfabeto, es un subconjunto)

**Comment by Baelfire18** [comment]
@HernanCabrera  Profesor yo comparo los largos de ambas claves y son iguales. Aún así no llego a traducir algo legible

**Comment by HernanCabrera** [comment]
Tiene que encontrar la proporcion (frecuencia) de letras en el texto encriptado.. luego, digamos que tiene el caracter X (X es cualquier caracter) con una frecuencia Xf.. entonces va a la lista de frecuencias y busca en freq (la lisa de frecuencias) y encuentra el % mas cercano a Xf de entre todos los porcentajes (eso significa que tendra que implementar alguna funcion de distancia entre los porcentajes calculados) y alli comienza a hacer la asignacion de todos los Xi y resolver empates... debiera darle algo aproximadamente a legible... por ejemplo una frase se veria del estilo:

"Enunciato de la larea"  en vez de enuncido de la tarea.

Si compara lo que encontró.. tendrá:

en orden algo como (es un ejemplo no mas)

l,m,t,a,f,g,x,r,x,b,w,q   y listo, no tiene mas letras.
Si lo maepa con el abecedario. .como lo hace?

Digamos que las frecuencias son:  a,e,i,o,u,m,n,l,r,t,p,f....,q,z,y,ñ,w
l -> a
m-> e
.....
w->p
q->f

Y que hace con el resto de las letras? por ejemplo la q, la z o la ñ?
