### ISSUE TITLE
[I1] Pregunta G 

### ISSUE THREAD

**Issue by Fernan-tess** [IIC2513-2021-1/projects#87]
En el enunciado dice que No hay letras acentuadas, pero encontré 5 "í"s en el texto. Se ignoran o las agrego a la cuenta de las ies?

**Comment by HernanCabrera** [comment]
Se ignoran

**Comment by sivicencio** [comment]
Les aconsejo revisar [la issue de FAQ](https://github.com/IIC2513-2021-1/projects/issues/75) antes de hacer una pregunta. Está ordenada por pregunta, por lo que pueden buscar qué se ha dicho al respecto y tener una respuesta más rápida. Esta pregunta, por ejemplo, fue respondida por Zoom y se encuentra en esa issue.
