### ISSUE TITLE
[I1]  Pregunta H

### ISSUE THREAD

**Issue by tamaralues** [IIC2513-2021-1/projects#88]
Hola! no me queda muy claro cual es la función de splitSample(), nosotros debemos crear y retornar esa estructura o se debe obtener de alguna parte?

**Comment by HernanCabrera** [comment]
Esa es la funcion.. splitSample() es una funcion que hace que el robot del rover divida la muestra en 4 partes y retorne la estrcutura que entregamos (que como estructura no se debe cambiar, pero para probar distintos escenarios, se porá cambiar el contenido) . Tal cual lo dices.. pero tambien debes implementar que splitSample() pueda devolver un error y que ese codigo de error suspenda toda ejecucion futura.(ahora,  como ves en callTest, en realidad el error (codio de error en realidad) es en "duro", asi que no te tomes mucho tiempo en eso.Despues a mano no mas se cambian condiciones d eexito y de error
