### ISSUE TITLE
[I1] Pregunta G

### ISSUE THREAD

**Issue by sebaelsaca** [IIC2513-2021-1/projects#91]
Hola! Es posible ocupar librerías aparte de Math, String y Array??

**Comment by fjcroquevielle** [comment]
Profesor, respecto a esta pregunta tengo la siguiente pregunta: busco aquella letra cuya frecuencia esta más cercana a la que estoy evaluando (respecto a su frecuencia en el texto). Para lo anterior comienzo evaluando aquella letra con mayor frecuencia en el texto y así hacia abajo. En consecuencia, a veces cierta letra no quedará vinculada a aquella que tenía frecuencia mas parecida en la tabla (debido a que una letra con mayor frecuencia en el texto pudo haber ocupado dicha letra de la tabla anteriormente debido a que era la que tenía más parecida y tenía mayor frecuencia entonces fue evaluada antes). Creo que es correcto ir evaluando de más importantancia a menos importancia.  A pesar de esto, cuesta leer la traducción, por eso pregunto. Saludos y muchas gracias!

**Comment by HernanCabrera** [comment]
La clave es que las letras de mayor frecuencia ya dan una aproximacion a lo que debiese ser el texto. Lo que puede afinar para mejorar la lectura del texto desencriptado es el algoritmo de empates, hay decimales involucrados, tal vez sondiea muchos de ellos o el algoritmo de distancias funciona bien para numeros grandes y no para pequeños. esos son pequeños ajustes que le permitirán mejorar la traduccion
