### ISSUE TITLE
[I1] Formulario de entrega

### ISSUE THREAD

**Issue by aigou42** [IIC2513-2021-1/projects#93]
Hola! Entregué un zip y después me di cuenta de que estaba dañado. Ya había cerrado chrome y ya no me ofrece modificar la respuesta, que puedo hacer? Subo otra respuesta nomás?

**Comment by sivicencio** [comment]
Hola. Sí, sube otra respuesta no más. Se considerará la última que envíes.

**Comment by aigou42** [comment]
Gracias!
