### ISSUE TITLE
Problema: Nombre de archivo enviado 

### ISSUE THREAD

**Issue by sofi-camino** [IIC2513-2021-1/projects#94]
Holiii, acabo de enviar mi zip pero como aún no me manejo del todo con mi máquina virtual, se envió como Apellido_Nombre_NumAlumno - Nombre Apellido.zip :( ¿Hay algo que pueda hacer? De verdad que juraba que era el nombre correcto :((

**Comment by sivicencio** [comment]
Puedes subir otra respuesta. El formulario permite múltiples envíos y se considerará el último enviado.

**Comment by sofi-camino** [comment]
Intenté enviar otra respuesta. Esta vez asegurándome de que el nombre estaba bien, pero cuando me llega el mail con mi respuesta, me sigue saliendo ese formato. Tengo miedo, ¿debería dejarlo así?

**Comment by sivicencio** [comment]
@sofi-camino Me informa @meretamal que la parte `- Nombre Apellido` es algo que agrega Google Form, por lo que no te preocupes. Mantiene el formato solicitado al principio, así que permite identificar bien que corresponde a tu solución.
